name: Build QR Codes

on:
  push:
    paths:
      - 'data/**.json'
      - '.github/workflows/qr.yaml'

jobs:
  qr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: pip install qrcode[pil]
    - run: pip install qrcode[pil] tqdm
    - run: pip install requests[pil]

    - run: python qr_batch.py

    - name: Commit QR codes
      run: |
        git config user.name "qr-bot"
        git config user.email "qr-bot@noreply"
        git add qr
        if ! git diff --cached --quiet; then
          git commit -m "ci: rebuild QR codes"
          git push
        fi
